###
GET http://localhost:5000/api/1/lockers

### 
POST http://localhost:5000/api/1/lockers/route
Content-Type: application/json

{
  "lockers_list": ["WRO88M","WRO911","WRO33A"], 
  "courier_latitude": 51.0, 
  "courier_longitude": 17.0
}

###
POST http://localhost:5000/api/1/here_api/directions
Content-Type: application/json
 
 {
   "path": ["courier", "WRO88M","WRO911","WRO33A", "courier"], 
   "courier_latitude": 51.09907, 
   "courier_longitude": 17.027580
}

###
GET http://localhost:5000/api/1/users
###
PUT http://localhost:5000/api/1/users
Content-Type: application/json
 
 {
   "username": "kamildudek", 
   "update_dict": [{"district": "srodmiescie"}], 
}

###
POST http://localhost:5000/api/1/users
Content-Type: application/json

 {
   "username": "kamildudek4", 
   "password": "asdasdasd", 
   "role": "admin",
   "district": "gaj"
}

###
DELETE  http://localhost:5000/api/1/users
Content-Type: application/json
 
 {
   "username": "kamildudek4", 
}
