###
GET http://localhost:5000/api/1/lockers

### 
POST http://localhost:5000/api/1/lockers/route
Content-Type: application/json

{
  "lockers_list": ["WRO88M","WRO911","WRO33A"], 
  "courier_latitude": 51.0, 
  "courier_longitude": 17.0
}

###
POST http://localhost:5000/api/1/here_api/directions
Content-Type: application/json
 
 {
   "path": ["courier", "WRO88M","WRO911","WRO33A", "courier"], 
   "courier_latitude": 51.09907, 
   "courier_longitude": 17.027580
}
