# basic API call
###
GET http://localhost:5000/api/1


# get place information
###
GET http://localhost:5000/api/1/here_api/51.0/17.0


# get route information
###
GET http://localhost:5000/api/1/here_api/51.0/17.0/51.02/17.02


# get directions
###
POST http://localhost:5000/api/1/here_api/directions
Content-Type: application/json
 
 {
   "path": ["courier", "WRO88M","WRO911","WRO33A", "courier"], 
   "courier_latitude": 51.09907, 
   "courier_longitude": 17.027580
}


# get lockers
###
GET http://localhost:5000/api/1/lockers


# get lockers from district
###
GET http://localhost:5000/api/1/lockers/srodmiescie


# get districts
###
GET http://localhost:5000/api/1/lockers/districts


# get optimal route
###
POST http://localhost:5000/api/1/lockers/route
Content-Type: application/json

{
  "lockers_list": ["WRO88M","WRO911","WRO33A"], 
  "courier_latitude": 51.09907, 
  "courier_longitude": 17.027580
}


# get users
###
GET http://localhost:5000/api/1/users


# add user
###
POST http://localhost:5000/api/1/users
Content-Type: application/json

{
  "username": "test_user", 
  "password": "test_user_password", 
  "role": "courier",
  "district": "gaj",
}


# update user
###
PUT http://localhost:5000/api/1/users
Content-Type: application/json

{
  "username": "kamildudek", 
  "update_dict": {"district": "new_district"},
}


# delete user
###
DELETE http://localhost:5000/api/1/users
Content-Type: application/json

{
  "username": "kamildudek", 
}


# login user
###
POST http://localhost:5000/api/1/users
Content-Type: application/json

{
  "username": "kamildudek",
  "password": "kamildudek_password", 
}
